name: CI

on:
  push:
    branches-ignore:
    - 'l10n_master'
    - 'gh-pages'

jobs:
  build:
    runs-on: windows-latest
    env:
      imgur_client_id: ${{ secrets.imgur_client_id }}
      yt_client_id: ${{ secrets.yt_client_id }}
      yt_client_secret: ${{ secrets.yt_client_secret }}
      choco_key: ${{ secrets.choco_key }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Cake
      run: dotnet tool install -g Cake.Tool --version 0.32.1
    - name: Run Cake script
      run: dotnet-cake
